#!/usr/bin/env python3
"""
indent2xml a python script to leverage indent2xml.py module and output
xml text from a tabbed structure file.
Copyright (C) 2010 Nathan Middleton

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
import indent2xml
from sys import argv
import os

if __name__ == '__main__':
	if len(argv) > 1 and os.path.exists(argv[1]):
		xml = indent2xml.parse(argv[1])
		print(xml)
	else:
		print('Please provided a valid filename.')
		
